name: Output Event Details on Issues
on:
  issues:
    types:
      - opened
    branches:
      - main
      - "dev-*"
      - "feat/**"
  workflow_dispatch:
  push:
    branches:
      - main
      - "dev-*"
      - "feat/**"
    paths-ignore:
      - ".github/workflows/*"
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event Details
        run: echo "${{ toJSON(github.event) }}" > event.json
      - name: Display Event Details
        run: cat event.json
